# This is a basic workflow to help you get started with Actions

name: Linux_Container_Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: Checkout
          uses: actions/checkout@v2
          with:
           path: main
 
        - name: Docker Login
          run: | 
            docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        
        - name: Build and Push
          run: |
            docker build main/code -f main/docker/Dockerfile.prod -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/roonr/media-uploader:${{ github.sha }} 
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/roonr/media-uploader:${{ github.sha }}
